import React from "react";
import { Route, Routes } from "react-router-dom";

import {
  Home,
  InnerPage,
  Category,
  Contacts,
  SearchResult,
} from "../Pages/User";
import FailPage from "../Pages/FailPage";

function UserInterface({
  localStoreStage,
  searchRequest,
  postCatRequest,
  postRequest,
  setPosthRequest,
  setNewsCatRequest,
  changeUrl,
  setPostCatRequest,
}) {
  const images = localStoreStage.images;

  return (
    <Routes>
      <Route
        exact
        path="/"
        element={
          <Home
            localStoreStage={localStoreStage}
            images={images}
            setPosthRequest={setPosthRequest}
            setPostCatRequest={setPostCatRequest}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/post"
        element={
          <InnerPage
            localStoreStage={localStoreStage}
            postRequest={postRequest}
            setPosthRequest={setPosthRequest}
            setPostCatRequest={setPostCatRequest}
            setNewsCatRequest={setNewsCatRequest}
            fetchType={false}
            images={images}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/newspage"
        element={
          <InnerPage
            localStoreStage={localStoreStage}
            postRequest={postRequest}
            setPosthRequest={setPosthRequest}
            setPostCatRequest={setPostCatRequest}
            setNewsCatRequest={setNewsCatRequest}
            fetchType={true}
            images={images}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/category"
        element={
          <Category
            localStoreStage={localStoreStage}
            setPosthRequest={setPosthRequest}
            postCatRequest={postCatRequest}
            setPostCatRequest={setPostCatRequest}
            setNewsCatRequest={setNewsCatRequest}
            fetchType={false}
            fetchCatNewsLoad={false}
            images={images}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/news/category"
        element={
          <Category
            localStoreStage={localStoreStage}
            setPosthRequest={setPosthRequest}
            postCatRequest={postCatRequest}
            setPostCatRequest={setPostCatRequest}
            setNewsCatRequest={setNewsCatRequest}
            fetchType={false}
            fetchCatNewsLoad={true}
            images={images}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/news"
        element={
          <Category
            localStoreStage={localStoreStage}
            setPosthRequest={setPosthRequest}
            postCatRequest={postCatRequest}
            setPostCatRequest={setPostCatRequest}
            setNewsCatRequest={setNewsCatRequest}
            fetchType={true}
            fetchCatNewsLoad={false}
            images={images}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/contacts"
        element={
          <Contacts
            localStoreStage={localStoreStage}
            images={images}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/searchresult"
        element={
          <SearchResult
            localStoreStage={localStoreStage}
            images={images}
            searchRequest={searchRequest}
            setPosthRequest={setPosthRequest}
            setPostCatRequest={setPostCatRequest}
            changeUrl={changeUrl}
          />
        }
      />
      <Route
        exact
        path="/*"
        element={
          <FailPage
            localStoreStage={localStoreStage}
            images={images}
            changeUrl={changeUrl}
          />
        }
      />
    </Routes>
  );
}

export default UserInterface;
